### ISSUE TITLE
voodooinput.kext not loaded

### ISSUE THREAD

**Issue by lioliy** [kprinssu/VoodooInput#2]
hello
new version of VoodooPS2Controller need this kext to use trackpad
so I use latest version OpenCore and clover but the kext can't loaded
opencore says oc: prelink injection voodooinput.kext () - invalid parameter
clover says Extra kext: EFI\CLOVER\kexts\10.14\VoodooInput.kext (v.1) but not loaded either
I ran
kextstat|grep -y voodoo but no voodooinput.kext shown

**Comment by mnfesq** [comment]
It loaded for me and give functionality to VoodooPS2Controller version 2.1.0.  I compiled my own VoodooInput.kext with Xcode but there is only a debug build for now.
<img width="525" alt="Untitled" src="https://user-images.githubusercontent.com/54817849/69986466-4de95580-14f2-11ea-8eed-6a24b3753911.png">

**Comment by bluetechdev** [comment]
It doesnt work for me.

**Comment by bluetechdev** [comment]
![image](https://user-images.githubusercontent.com/57758491/69996614-b49e5b80-1552-11ea-8e4f-9fd84665b4f5.png)

**Comment by mnfesq** [comment]
@bluetechdev Try getting rid of VoodooI2C and VoodooGPIO.  If your laptop uses I2C, you don't need PS2 and vice versa.

**Comment by bluetechdev** [comment]
> @bluetechdev Try getting rid of VoodooI2C and VoodooGPIO. If your laptop uses I2C, you don't need PS2 and vice versa.

I have an dell xps 9370, the trackpad represents itself both as a PS2 and I2c, but I got rid of the I2C and VoodooInput is still not fixed.. Could I maybe get your build kext?

**Comment by vit9696** [comment]
Well, look, is not it obvious that the kext is not compiled for 10.14 and below? Stay patient and wait for a fix or recompile yourself with Xcode 10 or so.

**Comment by bluetechdev** [comment]
> Well, look, is not it obvious that the kext is not compiled for 10.14 and below? Stay patient and wait for a fix or recompile yourself with Xcode 10 or so.

Oh, my apologies I hadnt noticed that yet, I am very sorry!

**Comment by bluetechdev** [comment]
@vit9696 I also saw that in the release notes of 2.0.4 you said that the caps locks thing was fixed. But whenever I press capslock, the light flashes and goes out. The capslock does work but the light doenst stay on when activated.

**Comment by vit9696** [comment]
I am not in charge of VoodooPS2 development. You can check https://github.com/acidanthera/bugtracker/issues/514 regarding caps lock issue though. Looks like it behaves differently for different hardware.

**Comment by usr-sse2** [comment]
@vit9696 Are there any deleted comments here? There isn't any word about Caps Lock, what did you reply to?

**Comment by vit9696** [comment]
@usr-sse2, hrm, I have it in my mail:

> @vit9696 I also saw that in the release notes of 2.0.4 you said that the caps locks thing was fixed. But whenever I press capslock, the light flashes and goes out. The capslock does work but the light doenst stay on when activated.

Most likely it was deleted by the author.

**Comment by vit9696** [comment]
Resolved in master.
