### ISSUE TITLE
Can't use trackpad and keyboard at the same time 

### ISSUE THREAD

**Issue by QiuMP** [kprinssu/VoodooInput#6]
My computer model is MSI GS75.

The trackpad doesn't work for a second when I press the keyboard.

**Comment by lioliy** [comment]
Me too
But the old version of voodooPS2 which did't need this kext same have this problem.
Perhaps not about this kext

**Comment by usr-sse2** [comment]
It’s a feature, not a bug. It was configured in System Preferences (“Ignore accidental trackpad input”) earlier, but now there’s no such option. You may set QuietTimeAfterTyping to 0 in Info.plist or via configuration SSDT.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by usr-sse2** [comment]
It’s really half a second, not a second.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
